import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br" className="dark">
            <body className={`antialiased`}>
                {children}

                <Toaster />

                <Footer />
            </body>
        </html>
    );
}
